analytics: {}
color:
  brandColors: []
  brandStrength: 0.334639
  lightness: 1
  rhythmicContrast: 0.753516
  saturation: 0.15909
cta: {}
layout_spectrum: 1
name: Moses Gsn
opengraph: {}
purpose: []
typography_spectrum: 0.668157
